### ISSUE TITLE
beta package naming convention needs to comply with dpkg requirements

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-installer-debian#106]
While upgrading `kolibri` from `0.14.0b16` to `0.14.0` noticed this message -

`dpkg: warning: downgrading kolibri from 0.14.0b16-0ubuntu1 to 0.14.0-0ubuntu1`

Should it have been *upgrading* instead of *downgrading*?

Found some guidance in a mailing list -
https://lists.debian.org/debian-dpkg/1998/06/msg00128.html

Suggestion:
0.14.0~b16 is considered less than 0.14.0.

**Comment by jredrejo** [comment]
The problem is you installed a binary packaged by the automated builidng in GitHub, packages uploaded to Launchpad have the official Debian criteria.
https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed/+packages

Github automated builds are not to be used with apt nor to be considered final packages.
