### ISSUE TITLE
"Package is of bad quality" error when installing 0.12.4-beta8 .deb under Ubuntu 14.04

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri-installer-debian#74]
### Observed behavior
Encountered a `Package is of bad quality.` error when trying to install 0.12.4-beta8 `.deb` from https://github.com/learningequality/kolibri/releases/tag/v0.12.4-beta8 under Ubuntu 14.04 VirtualBox machine.  See attached image.

### Expected behavior
There must be no error when trying to install `.deb` under Ubuntu 14.04.

### User-facing consequences
Although the user can still continue installing by choosing <kbd>Ignore and Install</kbd> - the `.deb` must not throw errors during installation.

### Errors and logs
See attached image.

### Steps to reproduce

1. Fire-up Ubuntu 14.04 VirtualBox - then update it to the latest upgrades.
1. Download 0.12.4-beta8 `.deb` from https://github.com/learningequality/kolibri/releases/tag/v0.12.4-beta8
1. Double-click the `.deb` and see the error window under the **Ubuntu Software Center**.

### Context
 * Kolibri version: 0.12.4-beta8
 * Operating system: Ubuntu 14.04 under VirtualBox download at https://drive.google.com/open?id=1KLUZTJ-QMYoomiMLoViD09fOAoYz4X5D - upgrade the packages first before installing Kolibri
 * Browser: N/A

/cc: @benjaoming @jredrejo 

![VirtualBox_Ubuntu 14 04_12_06_2019_12_14_11](https://user-images.githubusercontent.com/175580/59323926-5add7700-8d0f-11e9-80e8-d2380cec4049.png)

**Comment by jredrejo** [comment]
Packages from the https://github.com/learningequality/kolibri/releases page are not compatible with Ubuntu 14.04. Please use the kolibri-proposed or kolibri ppa to test that version of Ubuntu.

**Comment by benjaoming** [comment]
@jredrejo assuming this is because of bumping the Debian standards version? Since this finally and fully breaks 14.04 compatibility, I'm wondering if it was necessary as per recent odd indications that we might want to "sort of" support 14.04? Ah, it's confusing.. I was under the impression that we'd stop integration testing it, but just "letting it work" for as long as it didn't influence new features and we weren't making any guarantees (such as writing it in the documentation).

**Comment by indirectlylit** [comment]
In our official documentation we should continue to say that we only support 16.04+

However in practice we'll need to keep testing and supporting 14.04+ until we are confident that our partners have fully migrated. We can try to do this for 0.13.0 but it's not guaranteed

**Comment by radinamatic** [comment]
> In our official documentation we should continue to say that we only support 16.04+

Agreed, we'll keep it as it stands now!

**Comment by benjaoming** [comment]
@cpauya I think that the .deb built on Buildkite won't work on 14.04, I recall this error happening before. Only builds from Launchpad are backwards compatible because they're built on 12.04 or 14.04. Could you try a package from: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed

**Comment by cpauya** [comment]
@benjaoming The PPA package works (this is what I used as suggested by @jredrejo) and also installing via the `Terminal` by running `sudo dpkg -i...`.  Only when I double-click the `.deb` and when I try to install it in the Package Manager that the issue shows.

**Comment by benjaoming** [comment]
> Only when I double-click the .deb and when I try to install it in the Software Center that the issue shows.

But this is the .deb made by Buildkite, right?

**Comment by cpauya** [comment]
Yes @benjaoming - this is the BuildKite .deb I downloaded at https://github.com/learningequality/kolibri/releases
